### PR TITLE
move Enum to top of namespace

### PR DESCRIPTION
**Pull request by pelikhan**
Required to support TypeScript 2.0 compilation.

### CODE REVIEW

**Comment by pelikhan** [comment]
@sunfounder

**Comment by pelikhan** [comment]
@microbit-mark FYI

**Comment by microbit-mark** [comment]
@sunfounder Cavon, have messaged you on Slack also on 12th June. Can you action this PR please?

**Comment by sunfounder** [comment]
Hi dear 

Thanks for your advice,and can you tell the detail.thanks



Best Regards
Jake 

support@sunfounder.com
 
From: Guillaume Jenkins
Date: 2018-08-22 00:39
To: sunfounder/pxt-sloth
CC: SunFounder; Mention
Subject: Re: [sunfounder/pxt-sloth] move Enum to top of namespace (#4)
@sunfounder are you able to merge this soon? This change is necessary for the package to work in the next pxt-microbit version

**Comment by microbit-mark** [comment]
microbit-support:4049
Also messaged support@sunfounder.com in this ticket on 21st August

**Pull request merged**
